sources:
  npm: true
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
reviewed:
  npm:
    - abbrev
    - bcrypt-pbkdf
    - bin-links
    - byline
    - cacache
    - cidr-regex
    - color-convert-1.9.1
    - color-convert-1.9.3
    - color-convert-2.0.1
    - retry-0.12.0
    - sorted-object
    - source-map
    - spdx-exceptions-2.1.0
    - spdx-exceptions-2.3.0
    - ssri
    - string_decoder-1.1.1
    - string_decoder-1.3.0
    - typedarray
    - uglify-js
    - util-promisify
    - wcwidth
    - wordwrap
    - yargs
    - color-convert
    - colors
    - configstore
    - dotenv
    - duplexer2
    - duplexer3
    - encoding
    - figgy-pudding
    - fs.realpath
    - gentle-fs
    - glob
    - ignore
    - is-cidr
    - jsbn
    - json-parse-even-better-errors
    - json-schema
    - libnpm
    - libnpmhook
    - lodash
    - lodash._baseindexof
    - lodash._baseuniq
    - lodash._bindcallback
    - lodash._cacheindexof
    - lodash._createcache
    - lodash._createset
    - lodash._getnative
    - lodash._root
    - lodash.capitalize
    - lodash.clonedeep
    - lodash.escaperegexp
    - lodash.ismatch
    - lodash.isplainobject
    - lodash.isstring
    - lodash.mergewith
    - lodash.restparam
    - lodash.toarray
    - lodash.union
    - lodash.uniq
    - lodash.uniqby
    - lodash.without
    - make-fetch-happen
    - marked
    - minizlib
    - neo-async
    - normalize-package-data
    - npm
    - npm-audit-report
    - npm-install-checks
    - npm-lifecycle
    - npm-logical-tree
    - npm-pick-manifest
    - npm-registry-fetch
    - npm-user-validate
    - opener
    - path-is-inside
    - qs
    - rc
    - readable-stream
    - retry
    - spdx-exceptions
    - string_decoder
    - uri-js
